"""crear tabla de maestros

Revision ID: 35efd1c2adff
Revises: d0ce50ed0c79
Create Date: 2026-02-27 17:46:01.829139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35efd1c2adff'
down_revision = 'd0ce50ed0c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maestros',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellidos', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('create_Date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maestros')
    # ### end Alembic commands ###
